INSERT INTO jobs (job_id, user_id, company_name, title, description, requirements, skills, benefits, location, work_mode, job_type, industry, salary_range, experience_level, education_level, deadline, logo_path, employment_status, views, applications_count, del_flg, create_date, updated_date) VALUES
(1, 1, 'Công ty ABC', 'Java Developer', 'Phát triển ứng dụng web Spring Boot.', 'Kinh nghiệm Java >=1 năm', 'Java, Spring Boot, SQL', 'Bảo hiểm, thưởng', 'Hồ Chí Minh', 'Onsite', 'Full-time', 'IT', '10-15 triệu', 'Junior', 'Đại học', '2025-10-31', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(2, 1, 'Công ty ABC', 'Frontend Developer', 'Phát triển giao diện ReactJS.', 'Thành thạo ReactJS, HTML, CSS', 'ReactJS, JS, CSS', 'Thưởng dự án', 'Hà Nội', 'Remote', 'Full-time', 'IT', '12-18 triệu', 'Junior', 'Đại học', '2025-11-15', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(3, 2, 'Công ty XYZ', 'Python Developer', 'Backend Python/Django.', 'Python >=1 năm, Django', 'Python, Django, REST', 'Thưởng cuối năm', 'Đà Nẵng', 'Hybrid', 'Full-time', 'IT', '15-20 triệu', 'Junior', 'Đại học', '2025-11-30', 'xyz_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(4, 2, 'Công ty XYZ', 'QA Engineer', 'Kiểm thử phần mềm.', 'Kinh nghiệm QA, Automation', 'Selenium, Java', 'Bảo hiểm', 'Hà Nội', 'Onsite', 'Full-time', 'IT', '8-12 triệu', 'Junior', 'Đại học', '2025-12-15', 'xyz_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(5, 1, 'Công ty ABC', 'Project Manager', 'Quản lý dự án phần mềm.', 'PM >=2 năm', 'Agile, Scrum', 'Thưởng + bảo hiểm', 'Hồ Chí Minh', 'Onsite', 'Full-time', 'IT', '20-30 triệu', 'Mid', 'Đại học', '2025-12-01', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(6, 1, 'Công ty ABC', 'DevOps Engineer', 'Triển khai CI/CD.', 'Kinh nghiệm DevOps >=1 năm', 'Docker, Jenkins, AWS', 'Bảo hiểm', 'Hồ Chí Minh', 'Hybrid', 'Full-time', 'IT', '15-20 triệu', 'Junior', 'Đại học', '2025-11-20', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(7, 2, 'Công ty XYZ', 'Business Analyst', 'Phân tích nghiệp vụ.', 'BA >=1 năm', 'Excel, SQL, UML', 'Bảo hiểm, thưởng', 'Hà Nội', 'Onsite', 'Full-time', 'IT', '12-18 triệu', 'Junior', 'Đại học', '2025-12-10', 'xyz_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(8, 2, 'Công ty XYZ', 'Mobile Developer', 'Phát triển ứng dụng Android/iOS.', 'Kinh nghiệm >=1 năm', 'Kotlin, Swift, ReactNative', 'Bảo hiểm, thưởng', 'Đà Nẵng', 'Remote', 'Full-time', 'IT', '12-20 triệu', 'Junior', 'Đại học', '2025-11-25', 'xyz_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(9, 1, 'Công ty ABC', 'UI/UX Designer', 'Thiết kế giao diện và trải nghiệm.', 'Thành thạo Figma, Photoshop', 'Figma, Photoshop', 'Thưởng dự án', 'Hồ Chí Minh', 'Onsite', 'Full-time', 'Design', '10-15 triệu', 'Junior', 'Đại học', '2025-11-18', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW()),
(10, 1, 'Công ty ABC', 'Database Administrator', 'Quản trị cơ sở dữ liệu.', 'Kinh nghiệm MySQL, PostgreSQL >=2 năm', 'SQL, DBA', 'Bảo hiểm', 'Hà Nội', 'Onsite', 'Full-time', 'IT', '15-25 triệu', 'Mid', 'Đại học', '2025-12-05', 'abc_logo.png', 'Open', 0, 0, false, NOW(), NOW());